export type ShowLane = 'Seahawk Central' | 'Hawkstream'

export type Video = {
  title: string
  show: ShowLane
  label: string
  date: string
  duration: string
  image: string
  url: string
  featured?: boolean
}

export const videos: Video[] = [
  {
    title: 'A Look Back at the 2025-2026 School Year',
    show: 'Seahawk Central',
    label: 'Student Life',
    date: 'Apr 28, 2026',
    duration: '1:18',
    image: 'https://img.youtube.com/vi/8O3KQNsSCfQ/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=8O3KQNsSCfQV',
    featured: true,
  },
  {
    title: 'No Kings Protest, Immigration Attorney, Overflow Housing & Sports',
    show: 'Seahawk Central',
    label: 'News',
    date: 'Mar 31, 2026',
    duration: '10:03',
    image: 'https://img.youtube.com/vi/9nbEmsZZ5H0/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=9nbEmsZZ5H0',
  },
  {
    title: 'SGA Elections, Shooting Downtown, Protests, & Sports Update',
    show: 'Seahawk Central',
    label: 'News',
    date: 'Mar 18, 2026',
    duration: '10:03',
    image: 'https://img.youtube.com/vi/CYMv_v52Ud4/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=CYMv_v52Ud4',
  },
  {
    title: '2026 SGA President Debate',
    show: 'Seahawk Central',
    label: 'Student Life',
    date: 'Mar 16, 2026',
    duration: '52:39',
    image: 'https://img.youtube.com/vi/FD4JCLAUUt0/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=FD4JCLAUUt0',
  },
  {
    title: 'Sports Update',
    show: 'Seahawk Central',
    label: 'News',
    date: 'Mar 16, 2026',
    duration: '6:34',
    image: 'https://img.youtube.com/vi/4qgcphh4Yss/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=4qgcphh4Yss',
  },
  {
    title: 'UNCW Basketball Player Arrested, UNCW Vigil, & Round up on Sports',
    show: 'Seahawk Central',
    label: 'News',
    date: 'Feb 24, 2026',
    duration: '10:09',
    image: 'https://img.youtube.com/vi/3xJ22bDmqFw/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=3xJ22bDmqFw',
  },
  {
    title: 'UNCW Basketball Player Arrested, UNCW Vigil, & Round up on Sports',
    show: 'Seahawk Central',
    label: 'News',
    date: 'Mar 16, 2026',
    duration: '10:09',
    image: 'https://img.youtube.com/vi/3xJ22bDmqFw/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=3xJ22bDmqFw',
  },
  {
    title: 'Encore Magazine Launch/Homecoming & the latest on UNCW Sports',
    show: 'Seahawk Central',
    label: 'News',
    date: 'Feb 13, 2026',
    duration: '7:34',
    image: 'https://img.youtube.com/vi/93VmPxCH8gQ/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=93VmPxCH8gQ',
  },
  {
    title: 'MLK Parade/Homecoming & Sports Updates',
    show: 'Seahawk Central',
    label: 'News',
    date: 'Jan 28, 2026',
    duration: '5:15',
    image: 'https://img.youtube.com/vi/rw2n5mSjE0A/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=rw2n5mSjE0A',
  },
  {
    title: 'Josh Stein at UNCW, ICE raids affecting students, & Wagsiving',
    show: 'Seahawk Central',
    label: 'News',
    date: 'Nov 25, 2026',
    duration: '6:53',
    image: 'https://img.youtube.com/vi/h9tEZS06Vqs/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=h9tEZS06Vqs',
  },
  {
    title: 'New Resident Housing, Mass Amount of Dead Birds on Campus, & More',
    show: 'Seahawk Central',
    label: 'News',
    date: 'Nov 18, 2026',
    duration: '8:51',
    image: 'https://img.youtube.com/vi/8ZSfB6A55aQ/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=8ZSfB6A55aQ',
  },
  {
    title: 'Student led 5k Run, Underwater Pumpkin Carving, and Sports',
    show: 'Seahawk Central',
    label: 'News',
    date: 'Nov 5, 2026',
    duration: '4:22',
    image: 'https://img.youtube.com/vi/EU_r1P6qPWM/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=EU_r1P6qPWM',
  },
  {
    title: 'Seahawk Central Halloween Special 2025',
    show: 'Seahawk Central',
    label: 'News',
    date: 'Oct 31, 2026',
    duration: '5:55',
    image: 'https://img.youtube.com/vi/vaB16LppDJ8/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=vaB16LppDJ8',
  },
  {
    title: 'Political Neutrality at UNCW & Sports Highlights',
    show: 'Seahawk Central',
    label: 'News',
    date: 'Oct 28, 2026',
    duration: '8:18',
    image: 'https://img.youtube.com/vi/0giKnXhT35c/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=0giKnXhT35c',
  },
  {
    title: 'Mike Pence at UNCW & Sports Highlights',
    show: 'Seahawk Central',
    label: 'News',
    date: 'Oct 22, 2026',
    duration: '11:56',
    image: 'https://img.youtube.com/vi/Y3kn96V6vnE/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=Y3kn96V6vnE',
  },
  {
    title: 'DANCECON: Dance & A Conversation with Abby Lee Miller',
    show: 'Hawkstream',
    label: 'Interview',
    date: 'Oct 12, 2026',
    duration: '33:54',
    image: 'https://img.youtube.com/vi/pc8dIpYioNc/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=pc8dIpYioNc',
  },
  {
    title: 'Office of Military Affairs, Girls Lifting Club, & Sports Highlights',
    show: 'Seahawk Central',
    label: 'News',
    date: 'Oct 7, 2026',
    duration: '8:42',
    image: 'https://img.youtube.com/vi/pdGfbXErqIQ/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=pdGfbXErqIQ',
  },
  {
    title: 'Campus Safety, Hispanic Heritage Month, & Sports Highlights',
    show: 'Seahawk Central',
    label: 'News',
    date: 'Oct 2, 2026',
    duration: '11:15',
    image: 'https://img.youtube.com/vi/fJRHFV0cECY/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=fJRHFV0cECY',
  },
  {
    title: 'Doink Cast!',
    show: 'Hawkstream',
    label: 'Art',
    date: 'Mar 28, 2025',
    duration: '6:28',
    image: 'https://img.youtube.com/vi/7Xi0vyMYcok/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=7Xi0vyMYcok',
  },
  {
    title: '5 Star Hockey Prospects - Nice Try!',
    show: 'Hawkstream',
    label: 'Entertainment',
    date: 'Feb 24, 2025',
    duration: '9:31',
    image: 'https://img.youtube.com/vi/kb_waFJs8zs/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=kb_waFJs8zs',
  },
  {
    title: 'Where is Chess Club?? - Nice Try!',
    show: 'Hawkstream',
    label: 'Entertainment',
    date: 'Dec 2, 2024',
    duration: '8:27',
    image: 'https://img.youtube.com/vi/5U2hKj_glss/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=5U2hKj_glss',
  },
  {
    title: 'UNCW Water Polo - Nice Try!',
    show: 'Hawkstream',
    label: 'Entertainment',
    date: 'Oct 29, 2024',
    duration: '10:12',
    image: 'https://img.youtube.com/vi/IwaixFhDHyA/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=IwaixFhDHyA',
  },
]

export const stats = [
  { value: '25+', label: 'Years on air' },
  { value: `900+`, label: 'Episodes uploaded' },
  { value: '100%', label: 'Student produced' },
  { value: '', label: '' },
]

export const crew = [
  { role: 'President', name: 'Tucker Hall', number: '', image: '' },
  { role: 'Vice President', name: 'Myles Riesgaard', number: '', image: '' },
  { role: 'Studio Director', name: 'Heather Taylor', number: '', image: '' },
  { role: 'Studio Production Lead', name: 'Tucker Aaron', number: '', image: '' },
  { role: 'Sports Production Lead', name: 'Tucker Peterson', number: '', image: '' },
  { role: 'Lead Editor', name: 'Meredith Gordon-White', number: '', image: '' },
  { role: 'Hawkstream Executive Producer', name: 'Jack Tolley', number: '', image: '' },
]
